### ISSUE TITLE
Loras with similar names are not displayed correctly

### ISSUE THREAD

**Issue by azumukupoe** [JaredTherriault/ComfyUI-JNodes#17] opened 2024-09-23 13:57 UTC
Do you have a folder structure recommendation?

**Comment by JaredTherriault** [comment] 2024-09-28 02:39
Hi, can you show me what you mean?

**Comment by JaredTherriault** [comment] 2024-09-29 21:41
I see, so they're two different versions of the same loras and you expect the friendly name (before the parentheses) and link to correspond to the exact version rather than the overall lora. Is that a correct assessment?

**Comment by JaredTherriault** [comment] 2024-10-06 20:32
Ok, so let's try to debug. How does your folder structure look? Just a screenshot would work. 

The script gets data from the .info file with the same name as the lora, so it's usually best to separate loras and all their familiar data (info, screenshots, configs) into folders. If you're getting these from civit, I recommend Civit Model Downloader: https://civitai.com/models/98843/civit-model-downloader

It will automatically download loras with all images and info into individual folders per-lora. Works with embeddings too.

**Comment by Monty1836** [comment] 2024-10-12 06:14
The issue appears to be with the way finding metadata files is handled.  Specifically, when searching for similar filenames for things like image previews, if one file starts with the same string as another, then it will match the metadata files to both models.
![{90007503-6AC1-4419-BF0B-A5A5412BA0D8}](https://github.com/user-attachments/assets/96b1a8a9-be68-426b-9bec-5675190ea312)
In this case, it's even matching the preview for "test file.safetensors" as the first preview for "test.safetensors".
![{E177132B-1024-4E5A-89FD-23EE85809296}](https://github.com/user-attachments/assets/3105036c-3a71-414b-b56c-7b51ce068939)
The correct preview does match as well, and only to "test.safetensors", but it's being detected as the last preview in this case.
![{8D724100-1FFF-4E9A-9EC7-32492721CE57}](https://github.com/user-attachments/assets/7b2cd60d-302d-44c8-8dba-9b7e063180e5)

**Comment by JaredTherriault** [comment] 2024-11-28 04:47
I'm afraid this is something I won't fix. It was designed for folderized use, and if the end user wants to keep them all in one folder then this is something they will have to design their naming convention around.

Normally I'd want the UX to follow the path of least frustration, but there's really no good way to handle this aside from requiring some kind of manifest file, but that's more of a burden on the end user than putting them into a separate folder.

The issue here is that we need to match the lora to its image previews, and the images must have a differentiating factor in order to coexist in the same folder. The downloader I recommended uses a number per image, so that's what I went with.

Because of this number, we can't do an exact file name match for images, so we need to do an "includes" match. But that opens us up to the issue you described when there are multiple loras with similar names in the same folder.

We can't just chop off the number either and then do an exact match, because what if the user names one lora "test" and another "test1"? Then we chop off the number and we're left with just "test" putting us in the same predicament.

If anyone has any thoughts on how this can be implemented I'd love to hear your ideas! For now though I will close this as "won't fix". The recommendation is to use a subfolder per lora with all of its infos and preview images.

**Closed by JaredTherriault** 2024-11-28 04:47 UTC

**Comment by Monty1836** [comment] 2024-12-05 06:50
I don't know exactly how python's matching works, but if you can, searching the strict filename followed by exclusively any number of digits would potentially solve the issue without breaking compatibility with your downloader.  "test1.png" would match in that case, but not "TestA.png".  If you can use a literal string followed by a regular expression, then searching for the filename without extension followed by `(\d*).png` to it should match the name of the file on its own, or followed by any amount of numbers.  So it would match "test.png", "test1.png", and "test12345.png", but it would not match "test file.png", or "testA.png".
